name: Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug - Show OS info
      run: |
        echo "Running on: $(uname -s)"
        echo "Distribution: $(lsb_release -d | cut -f2)"
        echo "Python path: $(which python3)"
        echo "Python version: $(python3 --version)"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Make run_bot.sh executable
      run: chmod +x run_bot.sh

    - name: Run Telegram Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        YOUR_CHAT_ID: ${{ secrets.YOUR_CHAT_ID }}
      run: |
        echo "启动 Telegram 机器人..."
        ./run_bot.sh
