name: Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发
  repository_dispatch: # 允许通过API触发
    types: [run-bot-deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.action == 'run-bot-deployment'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug - Show trigger info
      run: |
        echo "工作流触发方式: ${{ github.event_name }}"
        echo "触发分支: ${{ github.ref }}"
        echo "仓库: ${{ github.repository }}"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Make run_bots.sh executable
      run: chmod +x run_bots.sh

    - name: Run Telegram Bots
      env:
        # 消息转发机器人的环境变量
        MESSAGE_BOT_TOKEN: ${{ secrets.MESSAGE_BOT_TOKEN }}
        YOUR_CHAT_ID: ${{ secrets.YOUR_CHAT_ID }}
        # 命令机器人的环境变量
        COMMAND_BOT_TOKEN: ${{ secrets.COMMAND_BOT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO: ${{ github.repository }}  # 使用自定义环境变量避免冲突
      run: |
        echo "启动 Telegram 机器人..."
        ./run_bots.sh