name: Telegram Bot Handler

on:
  workflow_dispatch:  # 允许手动触发
  repository_dispatch:  # 允许通过API触发
    types: [trigger-open-command]
  push:
    branches: [ main ]
    paths:
      - 'bot_handler.py'
      - '.github/workflows/telegram-bot.yml'
  schedule:
    # 每5小时运行一次，避免GitHub Actions 6小时限制
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 355  # 略小于6小时，避免超时
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run environment check
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TARGET_GROUP_ID: ${{ secrets.TARGET_GROUP_ID }}
        MONITOR_GROUP_ID: ${{ secrets.MONITOR_GROUP_ID }}
        RESPONSE_GROUP_ID: ${{ secrets.RESPONSE_GROUP_ID }}
        KEYWORDS: ${{ secrets.KEYWORDS }}
        ALLOWED_USER_ID: ${{ secrets.ALLOWED_USER_ID }}
        LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        KEYWORD_MATCH_MODE: ${{ secrets.KEYWORD_MATCH_MODE }}
        MESSAGE_FORMAT: ${{ secrets.MESSAGE_FORMAT }}
        FORWARD_BOT_MESSAGES: ${{ secrets.FORWARD_BOT_MESSAGES }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python check_env.py
        
    - name: Run Telegram Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TARGET_GROUP_ID: ${{ secrets.TARGET_GROUP_ID }}
        MONITOR_GROUP_ID: ${{ secrets.MONITOR_GROUP_ID }}
        RESPONSE_GROUP_ID: ${{ secrets.RESPONSE_GROUP_ID }}
        KEYWORDS: ${{ secrets.KEYWORDS }}
        ALLOWED_USER_ID: ${{ secrets.ALLOWED_USER_ID }}
        LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        KEYWORD_MATCH_MODE: ${{ secrets.KETWORD_MATCH_MODE }}
        MESSAGE_FORMAT: ${{ secrets.MESSAGE_FORMAT }}
        FORWARD_BOT_MESSAGES: ${{ secrets.FORWARD_BOT_MESSAGES }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python bot_handler.py
